cart/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
	url(r'^$',
		views.CartDetail.as_view(),
		name="cart_detail"),

	url(r'^add/(?P<product_id>\d+)/$',
		views.CartAdd.as_view(),
		name="cart_add"),

	url(r'^remove/(?P<product_id>\d+)/$',
		views.CartRemove.as_view(),
		name="cart_remove"),
]

namuh/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from shop import urls as shopUrls
from cart import urls as cartUrls
from orders import urls as ordersUrls
from main import urls as mainUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls



urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^paypal/',
        include(paypalUrls)),
    url(r'^payment/',
        include(paymentUrls,namespace='payment')),

    url(r'^shop/',
    	include(shopUrls,namespace='shop')),
    url(r'^cart/',
    	include(cartUrls,namespace='cart')),
    url(r'^orders/',
    	include(ordersUrls,namespace='orders')),
    url(r'^',
    	include(mainUrls,namespace='main')),

    url(
        regex=r'^media/(?P<path>.*)$',
        view='django.views.static.serve',
        kwargs={'document_root':settings.MEDIA_ROOT}),

]

if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL,
		document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
	url(r'^create/$',
		views.OrderCreate.as_view(),
		name="order_create"),
	
]

shop/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
	url(r'^$',
		views.ProductListView.as_view(),
		name='product_list'),

	url(r'^(?P<category_slug>[-\w]+)/$',
		views.ProductListView.as_view(),
		name='product_list_by_category'),

	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
		views.ProductDetailView.as_view(),
		name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUARNTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
	quantity=forms.TypedChoiceField(label="Cantidad",choices=PRODUCT_QUARNTITY_CHOICES,coerce=int)
	update=forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)
	

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.views.decorators.http import require_POST
# from django.utils.decorators import method_decorator
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.views.generic import View



class CartAdd(View):
	def post(self,request,product_id):
		cart=Cart(request)
		product=get_object_or_404(Product,id=product_id)
		form=CartAddProductForm(request.POST)
		if form.is_valid():
			cd=form.cleaned_data
			cart.add(product=product,quantity=cd['quantity'],
				update_quantity=cd['update'])
		return redirect('cart:cart_detail')

class CartRemove(View):
	def get(self,request,product_id):
		cart=Cart(request)
		product=get_object_or_404(Product,id=product_id)
		cart.remove(product)
		return redirect('cart:cart_detail')

class CartDetail(View):
	def get(self,request):
		cart=Cart(request)
		template="cart/detail.html"
		for item in cart:
			item['update_quantity_form']=CartAddProductForm(initial={'quantity':item['quantity'],'update':True})
		context={
		'cart':cart
		}
		return render(request,template,context)

cart/templates/cart/detail.html
{%extends 'base.html'%}
{%load static%}
{%block titulo%}Tu carrito de Compras{%endblock titulo%}

{%block content%}
<section class="container">


<h4>Tus compras:</h4>
<table>
	<thead>
	<tr class="grey lighten-4">
		<th>Imagen</th>
		<th>Producto</th>
		<th>Cantidad</th>
		<th>Quitar</th>
		<th>Precio Unitario</th>
		<th>Precio</th>
	</tr>
	</thead>
	<tbody>
		{%for item in cart%}
		{%with product=item.product%}
		<tr>
			<td>
				<a href="{{product.get_absolute_url}}">
					<img style="max-width:50px;" class="responsive-img" src="{%if product.image%}{{product.image.url}}{%else%}{%static 'img/photo_not_available.png'%}{%endif%}">
				</a>
			</td>
			<td>
				{{product.name}}
			</td>
			<td>
				<form action="{%url 'cart:cart_add' product.id%}" method="post">
					{{item.update_quantity_form.quantity}}
					{{item.update_quantity_form.update}}
					<input type="submit" value="Actualizar" class="grey lighten-4 waves-effect btn-flat">
					{%csrf_token%}
				</form>
			</td>
			<td>
				<a href="{%url 'cart:cart_remove' product.id%}"> Quitar </a>
			</td>
			<td class="num">
				$ {{item.price}}
			</td>
			<td class="num">
				$ {{item.total_price}}
			</td>
		</tr>
		{%endwith%}
		{%endfor%}
		<tr class="grey lighten-3">
			<td>Total</td>
			<td colspan='4'></td>
			<td class="num">
				$ {{cart.get_total_price}}
			</td>
		</tr>
	</tbody>
</table>

<p class="">
	<a href="{%url 'shop:product_list'%}" class="btn grey lighten-1 left">
		Continuar Comprando
	</a>
	<a class="btn grey right" href="{%url 'orders:order_create'%}">
		Pagar
	</a>
</p>

</section>
{%endblock content%}

{%block scripts%}

  {%endblock scripts%}