cart/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
	url(r'^$',
		views.CartDetail.as_view(),
		name="cart_detail"),

	url(r'^add/(?P<product_id>\d+)/$',
		views.CartAdd.as_view(),
		name="cart_add"),

	url(r'^remove/(?P<product_id>\d+)/$',
		views.CartRemove.as_view(),
		name="cart_remove"),
]

main/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$',
		views.Home.as_view(),
		name="home"),
	url(r'^nosotros/$',
		views.Nosotros.as_view(),
		name="nosotros"),
	url(r'^puntos/$',
		views.Selling.as_view(),
		name="selling"),
	url(r'^politicas/$',
		views.Policies.as_view(),
		name="policies"),
	url(r'^arch/$',
		views.Arch.as_view(),
		name="arch"),


]

namuh/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from shop import urls as shopUrls
from cart import urls as cartUrls
from orders import urls as ordersUrls
from main import urls as mainUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls



urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^paypal/',
        include(paypalUrls)),
    url(r'^payment/',
        include(paymentUrls,namespace='payment')),

    url(r'^shop/',
    	include(shopUrls,namespace='shop')),
    url(r'^cart/',
    	include(cartUrls,namespace='cart')),
    url(r'^orders/',
    	include(ordersUrls,namespace='orders')),
    url(r'^',
    	include(mainUrls,namespace='main')),

    url(
        regex=r'^media/(?P<path>.*)$',
        view='django.views.static.serve',
        kwargs={'document_root':settings.MEDIA_ROOT}),

]

if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL,
		document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views



urlpatterns=[
	url(r'^$',
		views.ProductListView.as_view(),
		name='product_list'),

	url(r'^(?P<category_slug>[-\w]+)/$',
		views.ProductListView.as_view(),
		name='product_list_by_category'),

	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
		views.ProductDetailView.as_view(),
		name='product_detail'),
]

templates/base.html
{%load static%}
<!DOCTYPE html>

<html>
<head>
	<title>{%block titulo%}Namuh{%endblock titulo%}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width:device-width">


   <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

  {%block estilos%}
  {%endblock estilos%}

	<link rel="stylesheet" type="text/css" href="{%static 'css/bliss.css'%}">
  <link rel="icon" 
      type="image/png" 
      href="{%static 'logo.png'%}">







</head>
<body>
	<nav class="gris">
    <div class="nav-wrapper">
      <a href="{%url 'main:home'%}" class="brand-logo black-text">
        <img class="brand" src="{%static 'logo_nav.png'%}">
      </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#!" class="grey-text">
          {%with total_items=cart|length%}
          {%if cart|length > 0%}
          <i class="fa fa-shopping-cart" aria-hidden="true"></i> 

          Tu carrito:
          <a class="grey-text" href="{%url 'cart:cart_detail'%}">
            {{total_items}} Articulo{{total_items|pluralize}}, ${{cart.get_total_price}}
          </a>
          {%else%}
          <span class="grey-text">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i> 
            <a class="grey-text" href="{%url 'shop:product_list'%}">Tu carrito está vacío.</a></span>
          {%endif%}
          {%endwith%}
        </a></li>
      </ul>
    </div>
  </nav>

	<div class="content main">

		{%block content%}
		{%endblock content%}

	</div>



<div class="gris">
        <footer id='footer' class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col s12 m12">

                <ul style="margin-top:0;">
                  <a href="{%url 'main:nosotros'%}">
                  <li class="menu">Nosotros</li>
                  </a>
                  <a href="{%url 'main:arch'%}">
                  <li class="menu">Espacio Arquitectonico</li>
                </a>
                  <a href="{%url 'main:policies'%}">
                  <li class="menu">Politicas</li>
                </a>
                  <li class="menu">Contacto</li>
                  <a href="{%url 'main:selling'%}">
                  <li class="menu">Puntos de venta</li>
                  </a>
                </ul>                
              
              </div>

            </div>
          </div>
          <div class="footer-copyright">
            <div class="row">
            


            <div class="boton col m4 s4">
            <strong>Suscribete</strong><br>
              Forma parte de nuestro news letter
            </div>

            <div class="col m5 s2 center">
              <img style="width:40px;" src="{%static 'logo.png'%}">
            </div>

      <div class="social col m2 s5">
            <a style="margin-right: 1rem;" class="grey-text" href="#!">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
            <a style="margin-right: 1rem;" class="grey-text" href="#!">
              <i class="fa fa-facebook-official" aria-hidden="true"></i>
            </a>
            <a style="margin-right: 1rem;" class="grey-text" href="#!">
              <i class="fa fa-pinterest-square" aria-hidden="true"></i>
            </a>
      </div>


            </div>
          </div>
        </footer>
</div>









<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
     
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

  <script>
 $(document).ready(function() {
    $('select').material_select();
  });
 </script>

  {%block scripts%}
  {%endblock scripts%}
</body>
</html>

templates/pagination.html
<div class="paginator">
<span class="step-links">
{%if page.has_previous%}
<a href="?page={{page.previous_page_number}}">
Anterior</a>
{%endif%}


<span class="current">
Pagina {{page.number}} de {{page.paginator.num_pages}}
</span>

{%if page.has_next%}
<a href="?page={{page.next_page_number}}">
Siguiente</a>
{%endif%}

</span>


</div>